name: CI

on:
  pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python {{cookiecutter.python_version}}
      uses: actions/setup-python@v1
      with:
        python-version: {{cookiecutter.python_version}}
    - name: python-linter
      run: |
        pip install --upgrade pip flake8
        flake8
  test:
    needs: lint
    env:
      AWS_DEFAULT_REGION: {{ cookiecutter.aws_default_region }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python {{cookiecutter.python_version}}
      uses: actions/setup-python@v1
      with:
        python-version: {{cookiecutter.python_version}}
    - name: Unit test for {{cookiecutter.lambda_file_name}}.py
      run: |
        pip install -r "requirements.dev.txt"
        coverage run -m pytest .
        coverage report
