name: hadolint

on:
  pull_request:
    paths:
    - '**/Dockerfile'

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: hadolint
      run: find . -name Dockerfile | xargs -I{} bash -c "echo [INFO] checking {}; docker run --rm -i hadolint/hadolint < {}"
